package AirlineInterfaceApp;


/**
* AirlineInterfaceApp/AirlineInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirlineInterface.idl.java
* Sunday, January 29, 2017 7:01:26 PM IST
*/

public interface AirlineInterface extends AirlineInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AirlineInterface
