package AirlineInterfaceApp;


/**
* AirlineInterfaceApp/AirlineInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirlineInterface.idl.java
* Sunday, January 29, 2017 7:01:26 PM IST
*/

public interface AirlineInterfaceOperations 
{
  String BookTicket (String FName, String Name, String Source, String Destination, int NoOfTickets);
  String CancelTicket (String FName, String Name, String Source, String Destination, int NoOfTickets);
  String Inventory ();
  String PassengerInfo ();
  void shutdown ();
} // interface AirlineInterfaceOperations
