package AirlineInterfaceApp;


/**
* AirlineInterfaceApp/AirlineInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirlineInterface.idl.java
* Sunday, January 29, 2017 7:01:26 PM IST
*/

public abstract class AirlineInterfacePOA extends org.omg.PortableServer.Servant
 implements AirlineInterfaceApp.AirlineInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("BookTicket", new java.lang.Integer (0));
    _methods.put ("CancelTicket", new java.lang.Integer (1));
    _methods.put ("Inventory", new java.lang.Integer (2));
    _methods.put ("PassengerInfo", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AirlineInterfaceApp/AirlineInterface/BookTicket
       {
         String FName = in.read_string ();
         String Name = in.read_string ();
         String Source = in.read_string ();
         String Destination = in.read_string ();
         int NoOfTickets = in.read_long ();
         String $result = null;
         $result = this.BookTicket (FName, Name, Source, Destination, NoOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // AirlineInterfaceApp/AirlineInterface/CancelTicket
       {
         String FName = in.read_string ();
         String Name = in.read_string ();
         String Source = in.read_string ();
         String Destination = in.read_string ();
         int NoOfTickets = in.read_long ();
         String $result = null;
         $result = this.CancelTicket (FName, Name, Source, Destination, NoOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // AirlineInterfaceApp/AirlineInterface/Inventory
       {
         String $result = null;
         $result = this.Inventory ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // AirlineInterfaceApp/AirlineInterface/PassengerInfo
       {
         String $result = null;
         $result = this.PassengerInfo ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // AirlineInterfaceApp/AirlineInterface/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AirlineInterfaceApp/AirlineInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AirlineInterface _this() 
  {
    return AirlineInterfaceHelper.narrow(
    super._this_object());
  }

  public AirlineInterface _this(org.omg.CORBA.ORB orb) 
  {
    return AirlineInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class AirlineInterfacePOA
