package AirlineInterfaceApp;

/**
* AirlineInterfaceApp/AirlineInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirlineInterface.idl.java
* Sunday, January 29, 2017 7:01:26 PM IST
*/

public final class AirlineInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public AirlineInterfaceApp.AirlineInterface value = null;

  public AirlineInterfaceHolder ()
  {
  }

  public AirlineInterfaceHolder (AirlineInterfaceApp.AirlineInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AirlineInterfaceApp.AirlineInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AirlineInterfaceApp.AirlineInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AirlineInterfaceApp.AirlineInterfaceHelper.type ();
  }

}
